##
# buildspec.yaml
# CodeBuild build specification; mainly re-inits the source (for pipeline), init components, and performs the requested
# action.
# @see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
##
# yamllint disable rule:indentation
---
version: 0.2

env:
  shell: bash
  variables:
    PACKER_VERSION: '1.9.4'
    PACKER_FILE: 'pipeline.json'

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y docker
      - service docker start
      - docker version

  pre_build:
    commands:
      - echo "Pre-build phase: Setting up tags and environment"
      - |
        TAG="latest"  # Ensure TAG is always set
        if [[ "$TARGET_ENV" == "int" ]]; then
          TAG="int"
        elif [[ "$ACTION" == "init" ]] || [[ "$PUBLISH" == "1" ]]; then
          TAG=$(git describe --tags "$CODEBUILD_RESOLVED_SOURCE_VERSION" || echo "latest")
        else
          echo "No pre_build steps required."
        fi
      - echo "Using TAG: $TAG"

  build:
    commands:
      - echo "Build phase: Executing build commands"
      - |
        if [[ "$ACTION" == "init" ]]; then
          echo "Nothing to build during initialization."
        elif [[ "$REDEPLOY" == "1" ]]; then
          make redeploy
        elif [[ "$PUBLISH" == "1" ]]; then
          make publish_all
        elif [[ "$TARGET_ENV" == "int" ]]; then
          PACKER_FILE=local.json make build_all
        else
          make build_all
        fi

artifacts:
  files:
    - '**/*'
